export const FETCH_COSTS_REQUEST="FETCH_COSTS_REQUEST";
export const FETCH_COSTS_FAILURE="FETCH_COSTS_FAILURE";
export const FETCH_COSTS_SUCCESS="FETCH_COSTS_SUCCESS";
export const POST_COSTS_SUCCESS="POST_COSTS_SUCCESS";
export const POST_COSTS_FAILURE="POST_COSTS_FAILURE";
export const DELETE_ONE_COST="DELETE_ONE_COST";
export const EDIT_ONE_COST="EDIT_ONE_COST";
export const FILTER_COSTS="FILTER_COSTS";